// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardTariffEntity.proto

package com.fanxi.service.message;

public final class CardTariffEntityProto {
  private CardTariffEntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CardTariffEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fanxi.CardTariffEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 tariff = 1;</code>
     */
    long getTariff();

    /**
     * <code>int64 cash = 2;</code>
     */
    long getCash();

    /**
     * <code>int64 cashGold = 3;</code>
     */
    long getCashGold();

    /**
     * <code>string description = 4;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code fanxi.CardTariffEntity}
   */
  public  static final class CardTariffEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fanxi.CardTariffEntity)
      CardTariffEntityOrBuilder {
    // Use CardTariffEntity.newBuilder() to construct.
    private CardTariffEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CardTariffEntity() {
      tariff_ = 0L;
      cash_ = 0L;
      cashGold_ = 0L;
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CardTariffEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              tariff_ = input.readInt64();
              break;
            }
            case 16: {

              cash_ = input.readInt64();
              break;
            }
            case 24: {

              cashGold_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fanxi.service.message.CardTariffEntityProto.internal_static_fanxi_CardTariffEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fanxi.service.message.CardTariffEntityProto.internal_static_fanxi_CardTariffEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity.class, com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity.Builder.class);
    }

    public static final int TARIFF_FIELD_NUMBER = 1;
    private long tariff_;
    /**
     * <code>int64 tariff = 1;</code>
     */
    public long getTariff() {
      return tariff_;
    }

    public static final int CASH_FIELD_NUMBER = 2;
    private long cash_;
    /**
     * <code>int64 cash = 2;</code>
     */
    public long getCash() {
      return cash_;
    }

    public static final int CASHGOLD_FIELD_NUMBER = 3;
    private long cashGold_;
    /**
     * <code>int64 cashGold = 3;</code>
     */
    public long getCashGold() {
      return cashGold_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 4;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tariff_ != 0L) {
        output.writeInt64(1, tariff_);
      }
      if (cash_ != 0L) {
        output.writeInt64(2, cash_);
      }
      if (cashGold_ != 0L) {
        output.writeInt64(3, cashGold_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tariff_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, tariff_);
      }
      if (cash_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, cash_);
      }
      if (cashGold_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, cashGold_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity)) {
        return super.equals(obj);
      }
      com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity other = (com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity) obj;

      boolean result = true;
      result = result && (getTariff()
          == other.getTariff());
      result = result && (getCash()
          == other.getCash());
      result = result && (getCashGold()
          == other.getCashGold());
      result = result && getDescription()
          .equals(other.getDescription());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARIFF_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTariff());
      hash = (37 * hash) + CASH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCash());
      hash = (37 * hash) + CASHGOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCashGold());
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fanxi.CardTariffEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fanxi.CardTariffEntity)
        com.fanxi.service.message.CardTariffEntityProto.CardTariffEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fanxi.service.message.CardTariffEntityProto.internal_static_fanxi_CardTariffEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fanxi.service.message.CardTariffEntityProto.internal_static_fanxi_CardTariffEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity.class, com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity.Builder.class);
      }

      // Construct using com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tariff_ = 0L;

        cash_ = 0L;

        cashGold_ = 0L;

        description_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fanxi.service.message.CardTariffEntityProto.internal_static_fanxi_CardTariffEntity_descriptor;
      }

      public com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity getDefaultInstanceForType() {
        return com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity.getDefaultInstance();
      }

      public com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity build() {
        com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity buildPartial() {
        com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity result = new com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity(this);
        result.tariff_ = tariff_;
        result.cash_ = cash_;
        result.cashGold_ = cashGold_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity) {
          return mergeFrom((com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity other) {
        if (other == com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity.getDefaultInstance()) return this;
        if (other.getTariff() != 0L) {
          setTariff(other.getTariff());
        }
        if (other.getCash() != 0L) {
          setCash(other.getCash());
        }
        if (other.getCashGold() != 0L) {
          setCashGold(other.getCashGold());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long tariff_ ;
      /**
       * <code>int64 tariff = 1;</code>
       */
      public long getTariff() {
        return tariff_;
      }
      /**
       * <code>int64 tariff = 1;</code>
       */
      public Builder setTariff(long value) {
        
        tariff_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 tariff = 1;</code>
       */
      public Builder clearTariff() {
        
        tariff_ = 0L;
        onChanged();
        return this;
      }

      private long cash_ ;
      /**
       * <code>int64 cash = 2;</code>
       */
      public long getCash() {
        return cash_;
      }
      /**
       * <code>int64 cash = 2;</code>
       */
      public Builder setCash(long value) {
        
        cash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cash = 2;</code>
       */
      public Builder clearCash() {
        
        cash_ = 0L;
        onChanged();
        return this;
      }

      private long cashGold_ ;
      /**
       * <code>int64 cashGold = 3;</code>
       */
      public long getCashGold() {
        return cashGold_;
      }
      /**
       * <code>int64 cashGold = 3;</code>
       */
      public Builder setCashGold(long value) {
        
        cashGold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cashGold = 3;</code>
       */
      public Builder clearCashGold() {
        
        cashGold_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 4;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 4;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 4;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 4;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:fanxi.CardTariffEntity)
    }

    // @@protoc_insertion_point(class_scope:fanxi.CardTariffEntity)
    private static final com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity();
    }

    public static com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CardTariffEntity>
        PARSER = new com.google.protobuf.AbstractParser<CardTariffEntity>() {
      public CardTariffEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CardTariffEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CardTariffEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CardTariffEntity> getParserForType() {
      return PARSER;
    }

    public com.fanxi.service.message.CardTariffEntityProto.CardTariffEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fanxi_CardTariffEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fanxi_CardTariffEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026CardTariffEntity.proto\022\005fanxi\"W\n\020CardT" +
      "ariffEntity\022\016\n\006tariff\030\001 \001(\003\022\014\n\004cash\030\002 \001(" +
      "\003\022\020\n\010cashGold\030\003 \001(\003\022\023\n\013description\030\004 \001(\t" +
      "B2\n\031com.fanxi.service.messageB\025CardTarif" +
      "fEntityProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_fanxi_CardTariffEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fanxi_CardTariffEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fanxi_CardTariffEntity_descriptor,
        new java.lang.String[] { "Tariff", "Cash", "CashGold", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
