// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfirmChangePhoneRequest.proto

package com.fanxi.service.message;

public final class ConfirmChangePhoneRequestProto {
  private ConfirmChangePhoneRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfirmChangePhoneRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fanxi.ConfirmChangePhoneRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.fanxi.BaseRequest baseReq = 1;</code>
     */
    boolean hasBaseReq();
    /**
     * <code>.fanxi.BaseRequest baseReq = 1;</code>
     */
    com.fanxi.service.message.BaseRequestProto.BaseRequest getBaseReq();
    /**
     * <code>.fanxi.BaseRequest baseReq = 1;</code>
     */
    com.fanxi.service.message.BaseRequestProto.BaseRequestOrBuilder getBaseReqOrBuilder();

    /**
     * <code>string forgetToken = 15;</code>
     */
    java.lang.String getForgetToken();
    /**
     * <code>string forgetToken = 15;</code>
     */
    com.google.protobuf.ByteString
        getForgetTokenBytes();

    /**
     * <code>string txnId = 16;</code>
     */
    java.lang.String getTxnId();
    /**
     * <code>string txnId = 16;</code>
     */
    com.google.protobuf.ByteString
        getTxnIdBytes();

    /**
     * <code>string otp = 17;</code>
     */
    java.lang.String getOtp();
    /**
     * <code>string otp = 17;</code>
     */
    com.google.protobuf.ByteString
        getOtpBytes();

    /**
     * <code>string phone = 18;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 18;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();
  }
  /**
   * Protobuf type {@code fanxi.ConfirmChangePhoneRequest}
   */
  public  static final class ConfirmChangePhoneRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fanxi.ConfirmChangePhoneRequest)
      ConfirmChangePhoneRequestOrBuilder {
    // Use ConfirmChangePhoneRequest.newBuilder() to construct.
    private ConfirmChangePhoneRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfirmChangePhoneRequest() {
      forgetToken_ = "";
      txnId_ = "";
      otp_ = "";
      phone_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ConfirmChangePhoneRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.fanxi.service.message.BaseRequestProto.BaseRequest.Builder subBuilder = null;
              if (baseReq_ != null) {
                subBuilder = baseReq_.toBuilder();
              }
              baseReq_ = input.readMessage(com.fanxi.service.message.BaseRequestProto.BaseRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseReq_);
                baseReq_ = subBuilder.buildPartial();
              }

              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              forgetToken_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              txnId_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              otp_ = s;
              break;
            }
            case 146: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fanxi.service.message.ConfirmChangePhoneRequestProto.internal_static_fanxi_ConfirmChangePhoneRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fanxi.service.message.ConfirmChangePhoneRequestProto.internal_static_fanxi_ConfirmChangePhoneRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest.class, com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest.Builder.class);
    }

    public static final int BASEREQ_FIELD_NUMBER = 1;
    private com.fanxi.service.message.BaseRequestProto.BaseRequest baseReq_;
    /**
     * <code>.fanxi.BaseRequest baseReq = 1;</code>
     */
    public boolean hasBaseReq() {
      return baseReq_ != null;
    }
    /**
     * <code>.fanxi.BaseRequest baseReq = 1;</code>
     */
    public com.fanxi.service.message.BaseRequestProto.BaseRequest getBaseReq() {
      return baseReq_ == null ? com.fanxi.service.message.BaseRequestProto.BaseRequest.getDefaultInstance() : baseReq_;
    }
    /**
     * <code>.fanxi.BaseRequest baseReq = 1;</code>
     */
    public com.fanxi.service.message.BaseRequestProto.BaseRequestOrBuilder getBaseReqOrBuilder() {
      return getBaseReq();
    }

    public static final int FORGETTOKEN_FIELD_NUMBER = 15;
    private volatile java.lang.Object forgetToken_;
    /**
     * <code>string forgetToken = 15;</code>
     */
    public java.lang.String getForgetToken() {
      java.lang.Object ref = forgetToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        forgetToken_ = s;
        return s;
      }
    }
    /**
     * <code>string forgetToken = 15;</code>
     */
    public com.google.protobuf.ByteString
        getForgetTokenBytes() {
      java.lang.Object ref = forgetToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        forgetToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TXNID_FIELD_NUMBER = 16;
    private volatile java.lang.Object txnId_;
    /**
     * <code>string txnId = 16;</code>
     */
    public java.lang.String getTxnId() {
      java.lang.Object ref = txnId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txnId_ = s;
        return s;
      }
    }
    /**
     * <code>string txnId = 16;</code>
     */
    public com.google.protobuf.ByteString
        getTxnIdBytes() {
      java.lang.Object ref = txnId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txnId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTP_FIELD_NUMBER = 17;
    private volatile java.lang.Object otp_;
    /**
     * <code>string otp = 17;</code>
     */
    public java.lang.String getOtp() {
      java.lang.Object ref = otp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        otp_ = s;
        return s;
      }
    }
    /**
     * <code>string otp = 17;</code>
     */
    public com.google.protobuf.ByteString
        getOtpBytes() {
      java.lang.Object ref = otp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 18;
    private volatile java.lang.Object phone_;
    /**
     * <code>string phone = 18;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 18;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseReq_ != null) {
        output.writeMessage(1, getBaseReq());
      }
      if (!getForgetTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, forgetToken_);
      }
      if (!getTxnIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, txnId_);
      }
      if (!getOtpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, otp_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, phone_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseReq());
      }
      if (!getForgetTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, forgetToken_);
      }
      if (!getTxnIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, txnId_);
      }
      if (!getOtpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, otp_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, phone_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest)) {
        return super.equals(obj);
      }
      com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest other = (com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest) obj;

      boolean result = true;
      result = result && (hasBaseReq() == other.hasBaseReq());
      if (hasBaseReq()) {
        result = result && getBaseReq()
            .equals(other.getBaseReq());
      }
      result = result && getForgetToken()
          .equals(other.getForgetToken());
      result = result && getTxnId()
          .equals(other.getTxnId());
      result = result && getOtp()
          .equals(other.getOtp());
      result = result && getPhone()
          .equals(other.getPhone());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseReq()) {
        hash = (37 * hash) + BASEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getBaseReq().hashCode();
      }
      hash = (37 * hash) + FORGETTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getForgetToken().hashCode();
      hash = (37 * hash) + TXNID_FIELD_NUMBER;
      hash = (53 * hash) + getTxnId().hashCode();
      hash = (37 * hash) + OTP_FIELD_NUMBER;
      hash = (53 * hash) + getOtp().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fanxi.ConfirmChangePhoneRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fanxi.ConfirmChangePhoneRequest)
        com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fanxi.service.message.ConfirmChangePhoneRequestProto.internal_static_fanxi_ConfirmChangePhoneRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fanxi.service.message.ConfirmChangePhoneRequestProto.internal_static_fanxi_ConfirmChangePhoneRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest.class, com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest.Builder.class);
      }

      // Construct using com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }
        forgetToken_ = "";

        txnId_ = "";

        otp_ = "";

        phone_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fanxi.service.message.ConfirmChangePhoneRequestProto.internal_static_fanxi_ConfirmChangePhoneRequest_descriptor;
      }

      public com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest getDefaultInstanceForType() {
        return com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest.getDefaultInstance();
      }

      public com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest build() {
        com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest buildPartial() {
        com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest result = new com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest(this);
        if (baseReqBuilder_ == null) {
          result.baseReq_ = baseReq_;
        } else {
          result.baseReq_ = baseReqBuilder_.build();
        }
        result.forgetToken_ = forgetToken_;
        result.txnId_ = txnId_;
        result.otp_ = otp_;
        result.phone_ = phone_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest) {
          return mergeFrom((com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest other) {
        if (other == com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest.getDefaultInstance()) return this;
        if (other.hasBaseReq()) {
          mergeBaseReq(other.getBaseReq());
        }
        if (!other.getForgetToken().isEmpty()) {
          forgetToken_ = other.forgetToken_;
          onChanged();
        }
        if (!other.getTxnId().isEmpty()) {
          txnId_ = other.txnId_;
          onChanged();
        }
        if (!other.getOtp().isEmpty()) {
          otp_ = other.otp_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fanxi.service.message.BaseRequestProto.BaseRequest baseReq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fanxi.service.message.BaseRequestProto.BaseRequest, com.fanxi.service.message.BaseRequestProto.BaseRequest.Builder, com.fanxi.service.message.BaseRequestProto.BaseRequestOrBuilder> baseReqBuilder_;
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      public boolean hasBaseReq() {
        return baseReqBuilder_ != null || baseReq_ != null;
      }
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      public com.fanxi.service.message.BaseRequestProto.BaseRequest getBaseReq() {
        if (baseReqBuilder_ == null) {
          return baseReq_ == null ? com.fanxi.service.message.BaseRequestProto.BaseRequest.getDefaultInstance() : baseReq_;
        } else {
          return baseReqBuilder_.getMessage();
        }
      }
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      public Builder setBaseReq(com.fanxi.service.message.BaseRequestProto.BaseRequest value) {
        if (baseReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseReq_ = value;
          onChanged();
        } else {
          baseReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      public Builder setBaseReq(
          com.fanxi.service.message.BaseRequestProto.BaseRequest.Builder builderForValue) {
        if (baseReqBuilder_ == null) {
          baseReq_ = builderForValue.build();
          onChanged();
        } else {
          baseReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      public Builder mergeBaseReq(com.fanxi.service.message.BaseRequestProto.BaseRequest value) {
        if (baseReqBuilder_ == null) {
          if (baseReq_ != null) {
            baseReq_ =
              com.fanxi.service.message.BaseRequestProto.BaseRequest.newBuilder(baseReq_).mergeFrom(value).buildPartial();
          } else {
            baseReq_ = value;
          }
          onChanged();
        } else {
          baseReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      public Builder clearBaseReq() {
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
          onChanged();
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      public com.fanxi.service.message.BaseRequestProto.BaseRequest.Builder getBaseReqBuilder() {
        
        onChanged();
        return getBaseReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      public com.fanxi.service.message.BaseRequestProto.BaseRequestOrBuilder getBaseReqOrBuilder() {
        if (baseReqBuilder_ != null) {
          return baseReqBuilder_.getMessageOrBuilder();
        } else {
          return baseReq_ == null ?
              com.fanxi.service.message.BaseRequestProto.BaseRequest.getDefaultInstance() : baseReq_;
        }
      }
      /**
       * <code>.fanxi.BaseRequest baseReq = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fanxi.service.message.BaseRequestProto.BaseRequest, com.fanxi.service.message.BaseRequestProto.BaseRequest.Builder, com.fanxi.service.message.BaseRequestProto.BaseRequestOrBuilder> 
          getBaseReqFieldBuilder() {
        if (baseReqBuilder_ == null) {
          baseReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fanxi.service.message.BaseRequestProto.BaseRequest, com.fanxi.service.message.BaseRequestProto.BaseRequest.Builder, com.fanxi.service.message.BaseRequestProto.BaseRequestOrBuilder>(
                  getBaseReq(),
                  getParentForChildren(),
                  isClean());
          baseReq_ = null;
        }
        return baseReqBuilder_;
      }

      private java.lang.Object forgetToken_ = "";
      /**
       * <code>string forgetToken = 15;</code>
       */
      public java.lang.String getForgetToken() {
        java.lang.Object ref = forgetToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          forgetToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string forgetToken = 15;</code>
       */
      public com.google.protobuf.ByteString
          getForgetTokenBytes() {
        java.lang.Object ref = forgetToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          forgetToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string forgetToken = 15;</code>
       */
      public Builder setForgetToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        forgetToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string forgetToken = 15;</code>
       */
      public Builder clearForgetToken() {
        
        forgetToken_ = getDefaultInstance().getForgetToken();
        onChanged();
        return this;
      }
      /**
       * <code>string forgetToken = 15;</code>
       */
      public Builder setForgetTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        forgetToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object txnId_ = "";
      /**
       * <code>string txnId = 16;</code>
       */
      public java.lang.String getTxnId() {
        java.lang.Object ref = txnId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txnId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string txnId = 16;</code>
       */
      public com.google.protobuf.ByteString
          getTxnIdBytes() {
        java.lang.Object ref = txnId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txnId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string txnId = 16;</code>
       */
      public Builder setTxnId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string txnId = 16;</code>
       */
      public Builder clearTxnId() {
        
        txnId_ = getDefaultInstance().getTxnId();
        onChanged();
        return this;
      }
      /**
       * <code>string txnId = 16;</code>
       */
      public Builder setTxnIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txnId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object otp_ = "";
      /**
       * <code>string otp = 17;</code>
       */
      public java.lang.String getOtp() {
        java.lang.Object ref = otp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          otp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string otp = 17;</code>
       */
      public com.google.protobuf.ByteString
          getOtpBytes() {
        java.lang.Object ref = otp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          otp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string otp = 17;</code>
       */
      public Builder setOtp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        otp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string otp = 17;</code>
       */
      public Builder clearOtp() {
        
        otp_ = getDefaultInstance().getOtp();
        onChanged();
        return this;
      }
      /**
       * <code>string otp = 17;</code>
       */
      public Builder setOtpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        otp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 18;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 18;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 18;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 18;</code>
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 18;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:fanxi.ConfirmChangePhoneRequest)
    }

    // @@protoc_insertion_point(class_scope:fanxi.ConfirmChangePhoneRequest)
    private static final com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest();
    }

    public static com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfirmChangePhoneRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConfirmChangePhoneRequest>() {
      public ConfirmChangePhoneRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConfirmChangePhoneRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfirmChangePhoneRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfirmChangePhoneRequest> getParserForType() {
      return PARSER;
    }

    public com.fanxi.service.message.ConfirmChangePhoneRequestProto.ConfirmChangePhoneRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fanxi_ConfirmChangePhoneRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fanxi_ConfirmChangePhoneRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037ConfirmChangePhoneRequest.proto\022\005fanxi" +
      "\032\021BaseRequest.proto\"\200\001\n\031ConfirmChangePho" +
      "neRequest\022#\n\007baseReq\030\001 \001(\0132\022.fanxi.BaseR" +
      "equest\022\023\n\013forgetToken\030\017 \001(\t\022\r\n\005txnId\030\020 \001" +
      "(\t\022\013\n\003otp\030\021 \001(\t\022\r\n\005phone\030\022 \001(\tB;\n\031com.fa" +
      "nxi.service.messageB\036ConfirmChangePhoneR" +
      "equestProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fanxi.service.message.BaseRequestProto.getDescriptor(),
        }, assigner);
    internal_static_fanxi_ConfirmChangePhoneRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fanxi_ConfirmChangePhoneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fanxi_ConfirmChangePhoneRequest_descriptor,
        new java.lang.String[] { "BaseReq", "ForgetToken", "TxnId", "Otp", "Phone", });
    com.fanxi.service.message.BaseRequestProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
