// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetGamVQMMTimesResponse.proto

package com.fanxi.service.message;

public final class GetGamVQMMTimesResponseProto {
  private GetGamVQMMTimesResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetGamVQMMTimesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fanxi.GetGamVQMMTimesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
     */
    boolean hasBaseResponse();
    /**
     * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
     */
    com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse getBaseResponse();
    /**
     * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
     */
    com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponseOrBuilder getBaseResponseOrBuilder();

    /**
     * <code>int32 times = 5;</code>
     */
    int getTimes();

    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    java.util.List<com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity> 
        getVqmmEntityList();
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity getVqmmEntity(int index);
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    int getVqmmEntityCount();
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    java.util.List<? extends com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder> 
        getVqmmEntityOrBuilderList();
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder getVqmmEntityOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code fanxi.GetGamVQMMTimesResponse}
   */
  public  static final class GetGamVQMMTimesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fanxi.GetGamVQMMTimesResponse)
      GetGamVQMMTimesResponseOrBuilder {
    // Use GetGamVQMMTimesResponse.newBuilder() to construct.
    private GetGamVQMMTimesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetGamVQMMTimesResponse() {
      times_ = 0;
      vqmmEntity_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetGamVQMMTimesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.Builder subBuilder = null;
              if (baseResponse_ != null) {
                subBuilder = baseResponse_.toBuilder();
              }
              baseResponse_ = input.readMessage(com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResponse_);
                baseResponse_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {

              times_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                vqmmEntity_ = new java.util.ArrayList<com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity>();
                mutable_bitField0_ |= 0x00000004;
              }
              vqmmEntity_.add(
                  input.readMessage(com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          vqmmEntity_ = java.util.Collections.unmodifiableList(vqmmEntity_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fanxi.service.message.GetGamVQMMTimesResponseProto.internal_static_fanxi_GetGamVQMMTimesResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fanxi.service.message.GetGamVQMMTimesResponseProto.internal_static_fanxi_GetGamVQMMTimesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse.class, com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse.Builder.class);
    }

    private int bitField0_;
    public static final int BASERESPONSE_FIELD_NUMBER = 1;
    private com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse baseResponse_;
    /**
     * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
     */
    public boolean hasBaseResponse() {
      return baseResponse_ != null;
    }
    /**
     * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
     */
    public com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse getBaseResponse() {
      return baseResponse_ == null ? com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.getDefaultInstance() : baseResponse_;
    }
    /**
     * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
     */
    public com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponseOrBuilder getBaseResponseOrBuilder() {
      return getBaseResponse();
    }

    public static final int TIMES_FIELD_NUMBER = 5;
    private int times_;
    /**
     * <code>int32 times = 5;</code>
     */
    public int getTimes() {
      return times_;
    }

    public static final int VQMMENTITY_FIELD_NUMBER = 6;
    private java.util.List<com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity> vqmmEntity_;
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    public java.util.List<com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity> getVqmmEntityList() {
      return vqmmEntity_;
    }
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    public java.util.List<? extends com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder> 
        getVqmmEntityOrBuilderList() {
      return vqmmEntity_;
    }
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    public int getVqmmEntityCount() {
      return vqmmEntity_.size();
    }
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    public com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity getVqmmEntity(int index) {
      return vqmmEntity_.get(index);
    }
    /**
     * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
     */
    public com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder getVqmmEntityOrBuilder(
        int index) {
      return vqmmEntity_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseResponse_ != null) {
        output.writeMessage(1, getBaseResponse());
      }
      if (times_ != 0) {
        output.writeInt32(5, times_);
      }
      for (int i = 0; i < vqmmEntity_.size(); i++) {
        output.writeMessage(6, vqmmEntity_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseResponse_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseResponse());
      }
      if (times_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, times_);
      }
      for (int i = 0; i < vqmmEntity_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, vqmmEntity_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse)) {
        return super.equals(obj);
      }
      com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse other = (com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse) obj;

      boolean result = true;
      result = result && (hasBaseResponse() == other.hasBaseResponse());
      if (hasBaseResponse()) {
        result = result && getBaseResponse()
            .equals(other.getBaseResponse());
      }
      result = result && (getTimes()
          == other.getTimes());
      result = result && getVqmmEntityList()
          .equals(other.getVqmmEntityList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseResponse()) {
        hash = (37 * hash) + BASERESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getBaseResponse().hashCode();
      }
      hash = (37 * hash) + TIMES_FIELD_NUMBER;
      hash = (53 * hash) + getTimes();
      if (getVqmmEntityCount() > 0) {
        hash = (37 * hash) + VQMMENTITY_FIELD_NUMBER;
        hash = (53 * hash) + getVqmmEntityList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fanxi.GetGamVQMMTimesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fanxi.GetGamVQMMTimesResponse)
        com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fanxi.service.message.GetGamVQMMTimesResponseProto.internal_static_fanxi_GetGamVQMMTimesResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fanxi.service.message.GetGamVQMMTimesResponseProto.internal_static_fanxi_GetGamVQMMTimesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse.class, com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse.Builder.class);
      }

      // Construct using com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVqmmEntityFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (baseResponseBuilder_ == null) {
          baseResponse_ = null;
        } else {
          baseResponse_ = null;
          baseResponseBuilder_ = null;
        }
        times_ = 0;

        if (vqmmEntityBuilder_ == null) {
          vqmmEntity_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          vqmmEntityBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fanxi.service.message.GetGamVQMMTimesResponseProto.internal_static_fanxi_GetGamVQMMTimesResponse_descriptor;
      }

      public com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse getDefaultInstanceForType() {
        return com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse.getDefaultInstance();
      }

      public com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse build() {
        com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse buildPartial() {
        com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse result = new com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (baseResponseBuilder_ == null) {
          result.baseResponse_ = baseResponse_;
        } else {
          result.baseResponse_ = baseResponseBuilder_.build();
        }
        result.times_ = times_;
        if (vqmmEntityBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            vqmmEntity_ = java.util.Collections.unmodifiableList(vqmmEntity_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.vqmmEntity_ = vqmmEntity_;
        } else {
          result.vqmmEntity_ = vqmmEntityBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse) {
          return mergeFrom((com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse other) {
        if (other == com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse.getDefaultInstance()) return this;
        if (other.hasBaseResponse()) {
          mergeBaseResponse(other.getBaseResponse());
        }
        if (other.getTimes() != 0) {
          setTimes(other.getTimes());
        }
        if (vqmmEntityBuilder_ == null) {
          if (!other.vqmmEntity_.isEmpty()) {
            if (vqmmEntity_.isEmpty()) {
              vqmmEntity_ = other.vqmmEntity_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureVqmmEntityIsMutable();
              vqmmEntity_.addAll(other.vqmmEntity_);
            }
            onChanged();
          }
        } else {
          if (!other.vqmmEntity_.isEmpty()) {
            if (vqmmEntityBuilder_.isEmpty()) {
              vqmmEntityBuilder_.dispose();
              vqmmEntityBuilder_ = null;
              vqmmEntity_ = other.vqmmEntity_;
              bitField0_ = (bitField0_ & ~0x00000004);
              vqmmEntityBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVqmmEntityFieldBuilder() : null;
            } else {
              vqmmEntityBuilder_.addAllMessages(other.vqmmEntity_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse baseResponse_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse, com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.Builder, com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponseOrBuilder> baseResponseBuilder_;
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      public boolean hasBaseResponse() {
        return baseResponseBuilder_ != null || baseResponse_ != null;
      }
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      public com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse getBaseResponse() {
        if (baseResponseBuilder_ == null) {
          return baseResponse_ == null ? com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.getDefaultInstance() : baseResponse_;
        } else {
          return baseResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      public Builder setBaseResponse(com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse value) {
        if (baseResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResponse_ = value;
          onChanged();
        } else {
          baseResponseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      public Builder setBaseResponse(
          com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.Builder builderForValue) {
        if (baseResponseBuilder_ == null) {
          baseResponse_ = builderForValue.build();
          onChanged();
        } else {
          baseResponseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      public Builder mergeBaseResponse(com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse value) {
        if (baseResponseBuilder_ == null) {
          if (baseResponse_ != null) {
            baseResponse_ =
              com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.newBuilder(baseResponse_).mergeFrom(value).buildPartial();
          } else {
            baseResponse_ = value;
          }
          onChanged();
        } else {
          baseResponseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      public Builder clearBaseResponse() {
        if (baseResponseBuilder_ == null) {
          baseResponse_ = null;
          onChanged();
        } else {
          baseResponse_ = null;
          baseResponseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      public com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.Builder getBaseResponseBuilder() {
        
        onChanged();
        return getBaseResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      public com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponseOrBuilder getBaseResponseOrBuilder() {
        if (baseResponseBuilder_ != null) {
          return baseResponseBuilder_.getMessageOrBuilder();
        } else {
          return baseResponse_ == null ?
              com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.getDefaultInstance() : baseResponse_;
        }
      }
      /**
       * <code>.fanxi.RestfulBaseResponse baseResponse = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse, com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.Builder, com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponseOrBuilder> 
          getBaseResponseFieldBuilder() {
        if (baseResponseBuilder_ == null) {
          baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse, com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponse.Builder, com.fanxi.service.message.RestfulBaseResponseProto.RestfulBaseResponseOrBuilder>(
                  getBaseResponse(),
                  getParentForChildren(),
                  isClean());
          baseResponse_ = null;
        }
        return baseResponseBuilder_;
      }

      private int times_ ;
      /**
       * <code>int32 times = 5;</code>
       */
      public int getTimes() {
        return times_;
      }
      /**
       * <code>int32 times = 5;</code>
       */
      public Builder setTimes(int value) {
        
        times_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 times = 5;</code>
       */
      public Builder clearTimes() {
        
        times_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity> vqmmEntity_ =
        java.util.Collections.emptyList();
      private void ensureVqmmEntityIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          vqmmEntity_ = new java.util.ArrayList<com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity>(vqmmEntity_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder> vqmmEntityBuilder_;

      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public java.util.List<com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity> getVqmmEntityList() {
        if (vqmmEntityBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vqmmEntity_);
        } else {
          return vqmmEntityBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public int getVqmmEntityCount() {
        if (vqmmEntityBuilder_ == null) {
          return vqmmEntity_.size();
        } else {
          return vqmmEntityBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity getVqmmEntity(int index) {
        if (vqmmEntityBuilder_ == null) {
          return vqmmEntity_.get(index);
        } else {
          return vqmmEntityBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder setVqmmEntity(
          int index, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity value) {
        if (vqmmEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVqmmEntityIsMutable();
          vqmmEntity_.set(index, value);
          onChanged();
        } else {
          vqmmEntityBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder setVqmmEntity(
          int index, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder builderForValue) {
        if (vqmmEntityBuilder_ == null) {
          ensureVqmmEntityIsMutable();
          vqmmEntity_.set(index, builderForValue.build());
          onChanged();
        } else {
          vqmmEntityBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder addVqmmEntity(com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity value) {
        if (vqmmEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVqmmEntityIsMutable();
          vqmmEntity_.add(value);
          onChanged();
        } else {
          vqmmEntityBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder addVqmmEntity(
          int index, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity value) {
        if (vqmmEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVqmmEntityIsMutable();
          vqmmEntity_.add(index, value);
          onChanged();
        } else {
          vqmmEntityBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder addVqmmEntity(
          com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder builderForValue) {
        if (vqmmEntityBuilder_ == null) {
          ensureVqmmEntityIsMutable();
          vqmmEntity_.add(builderForValue.build());
          onChanged();
        } else {
          vqmmEntityBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder addVqmmEntity(
          int index, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder builderForValue) {
        if (vqmmEntityBuilder_ == null) {
          ensureVqmmEntityIsMutable();
          vqmmEntity_.add(index, builderForValue.build());
          onChanged();
        } else {
          vqmmEntityBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder addAllVqmmEntity(
          java.lang.Iterable<? extends com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity> values) {
        if (vqmmEntityBuilder_ == null) {
          ensureVqmmEntityIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vqmmEntity_);
          onChanged();
        } else {
          vqmmEntityBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder clearVqmmEntity() {
        if (vqmmEntityBuilder_ == null) {
          vqmmEntity_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          vqmmEntityBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public Builder removeVqmmEntity(int index) {
        if (vqmmEntityBuilder_ == null) {
          ensureVqmmEntityIsMutable();
          vqmmEntity_.remove(index);
          onChanged();
        } else {
          vqmmEntityBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder getVqmmEntityBuilder(
          int index) {
        return getVqmmEntityFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder getVqmmEntityOrBuilder(
          int index) {
        if (vqmmEntityBuilder_ == null) {
          return vqmmEntity_.get(index);  } else {
          return vqmmEntityBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public java.util.List<? extends com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder> 
           getVqmmEntityOrBuilderList() {
        if (vqmmEntityBuilder_ != null) {
          return vqmmEntityBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vqmmEntity_);
        }
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder addVqmmEntityBuilder() {
        return getVqmmEntityFieldBuilder().addBuilder(
            com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder addVqmmEntityBuilder(
          int index) {
        return getVqmmEntityFieldBuilder().addBuilder(
            index, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .fanxi.VQMMTimesEntity vqmmEntity = 6;</code>
       */
      public java.util.List<com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder> 
           getVqmmEntityBuilderList() {
        return getVqmmEntityFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder> 
          getVqmmEntityFieldBuilder() {
        if (vqmmEntityBuilder_ == null) {
          vqmmEntityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntity.Builder, com.fanxi.service.message.VQMMTimesEntityProto.VQMMTimesEntityOrBuilder>(
                  vqmmEntity_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          vqmmEntity_ = null;
        }
        return vqmmEntityBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:fanxi.GetGamVQMMTimesResponse)
    }

    // @@protoc_insertion_point(class_scope:fanxi.GetGamVQMMTimesResponse)
    private static final com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse();
    }

    public static com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetGamVQMMTimesResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetGamVQMMTimesResponse>() {
      public GetGamVQMMTimesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetGamVQMMTimesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetGamVQMMTimesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetGamVQMMTimesResponse> getParserForType() {
      return PARSER;
    }

    public com.fanxi.service.message.GetGamVQMMTimesResponseProto.GetGamVQMMTimesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fanxi_GetGamVQMMTimesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fanxi_GetGamVQMMTimesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035GetGamVQMMTimesResponse.proto\022\005fanxi\032\031" +
      "RestfulBaseResponse.proto\032\025VQMMTimesEnti" +
      "ty.proto\"\206\001\n\027GetGamVQMMTimesResponse\0220\n\014" +
      "baseResponse\030\001 \001(\0132\032.fanxi.RestfulBaseRe" +
      "sponse\022\r\n\005times\030\005 \001(\005\022*\n\nvqmmEntity\030\006 \003(" +
      "\0132\026.fanxi.VQMMTimesEntityB9\n\031com.fanxi.s" +
      "ervice.messageB\034GetGamVQMMTimesResponseP" +
      "rotob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fanxi.service.message.RestfulBaseResponseProto.getDescriptor(),
          com.fanxi.service.message.VQMMTimesEntityProto.getDescriptor(),
        }, assigner);
    internal_static_fanxi_GetGamVQMMTimesResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fanxi_GetGamVQMMTimesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fanxi_GetGamVQMMTimesResponse_descriptor,
        new java.lang.String[] { "BaseResponse", "Times", "VqmmEntity", });
    com.fanxi.service.message.RestfulBaseResponseProto.getDescriptor();
    com.fanxi.service.message.VQMMTimesEntityProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
