// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: History.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HistoryRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HistoryRoot : GPBRootObject
@end

#pragma mark - History

typedef GPB_ENUM(History_FieldNumber) {
  History_FieldNumber_TxnId = 1,
  History_FieldNumber_DtCreated = 2,
  History_FieldNumber_Service = 3,
  History_FieldNumber_Cash = 4,
  History_FieldNumber_Balance = 5,
  History_FieldNumber_Decription = 6,
};

@interface History : GPBMessage

@property(nonatomic, readwrite) int64_t txnId;

@property(nonatomic, readwrite) int64_t dtCreated;

@property(nonatomic, readwrite, copy, null_resettable) NSString *service;

@property(nonatomic, readwrite) int64_t cash;

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite, copy, null_resettable) NSString *decription;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
