// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "RegisterResponse.pbobjc.h"
 #import "UserDetail.pbobjc.h"
 #import "RestfulBaseResponse.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - RegisterResponseRoot

@implementation RegisterResponseRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - RegisterResponseRoot_FileDescriptor

static GPBFileDescriptor *RegisterResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"fanxi"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - RegisterResponse

@implementation RegisterResponse

@dynamic hasBaseResponse, baseResponse;
@dynamic hasUser, user;
@dynamic server;
@dynamic isForceUpdate;
@dynamic URLDownload;
@dynamic contentNewVersion;
@dynamic adv;
@dynamic type;
@dynamic registerToken;
@dynamic captcha;
@dynamic variantArray, variantArray_Count;

typedef struct RegisterResponse__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  RestfulBaseResponse *baseResponse;
  UserDetail *user;
  NSString *server;
  NSString *URLDownload;
  NSString *contentNewVersion;
  NSString *adv;
  NSString *registerToken;
  NSString *captcha;
  NSMutableArray *variantArray;
} RegisterResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseResponse",
        .dataTypeSpecific.className = GPBStringifySymbol(RestfulBaseResponse),
        .number = RegisterResponse_FieldNumber_BaseResponse,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, baseResponse),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(UserDetail),
        .number = RegisterResponse_FieldNumber_User,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, user),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "server",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_Server,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, server),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isForceUpdate",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_IsForceUpdate,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "URLDownload",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_URLDownload,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, URLDownload),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "contentNewVersion",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_ContentNewVersion,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, contentNewVersion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "adv",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_Adv,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, adv),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_Type,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "registerToken",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_RegisterToken,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, registerToken),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "captcha",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_Captcha,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, captcha),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "variantArray",
        .dataTypeSpecific.className = NULL,
        .number = RegisterResponse_FieldNumber_VariantArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RegisterResponse__storage_, variantArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RegisterResponse class]
                                     rootClass:[RegisterResponseRoot class]
                                          file:RegisterResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RegisterResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001\014\000\007\r\000\010!!)\000\t\021\000\014\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
