// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TurnResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "TurnResponse.pbobjc.h"
 #import "BaseResponse.pbobjc.h"
 #import "Player.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - TurnResponseRoot

@implementation TurnResponseRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - TurnResponseRoot_FileDescriptor

static GPBFileDescriptor *TurnResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"fanxi"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - TurnResponse

@implementation TurnResponse

@dynamic hasBaseResponse, baseResponse;
@dynamic zoneId;
@dynamic tableIndex;
@dynamic matchId;
@dynamic phomCard;
@dynamic nextId;
@dynamic currId;
@dynamic tienlenCards;
@dynamic isDuty;
@dynamic isGiveup;
@dynamic isNewRound;
@dynamic autoTime;
@dynamic fightInfoArray, fightInfoArray_Count;
@dynamic fightPlayersArray, fightPlayersArray_Count;

typedef struct TurnResponse__storage_ {
  uint32_t _has_storage_[1];
  int32_t zoneId;
  int32_t tableIndex;
  int32_t phomCard;
  int32_t autoTime;
  BaseResponse *baseResponse;
  NSString *matchId;
  NSString *nextId;
  NSString *currId;
  NSString *tienlenCards;
  NSMutableArray *fightInfoArray;
  NSMutableArray *fightPlayersArray;
} TurnResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseResponse",
        .dataTypeSpecific.className = GPBStringifySymbol(BaseResponse),
        .number = TurnResponse_FieldNumber_BaseResponse,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, baseResponse),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "zoneId",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_ZoneId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, zoneId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "tableIndex",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_TableIndex,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, tableIndex),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "matchId",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_MatchId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, matchId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "phomCard",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_PhomCard,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, phomCard),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "nextId",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_NextId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, nextId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "currId",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_CurrId,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, currId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "tienlenCards",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_TienlenCards,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, tienlenCards),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isDuty",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_IsDuty,
        .hasIndex = 8,
        .offset = 9,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "isGiveup",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_IsGiveup,
        .hasIndex = 10,
        .offset = 11,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "isNewRound",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_IsNewRound,
        .hasIndex = 12,
        .offset = 13,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "autoTime",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_AutoTime,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, autoTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "fightInfoArray",
        .dataTypeSpecific.className = NULL,
        .number = TurnResponse_FieldNumber_FightInfoArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, fightInfoArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fightPlayersArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Player),
        .number = TurnResponse_FieldNumber_FightPlayersArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TurnResponse__storage_, fightPlayersArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TurnResponse class]
                                     rootClass:[TurnResponseRoot class]
                                          file:TurnResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TurnResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\016\001\014\000\004\006\000\005\n\000\006\007\000\007\010\000\010\006\000\t\006\000\n\014\000\013\006\000\014\010\000\r\n\000\016\010\000\017\000f"
        "ightInfo\000\020\000fightPlayers\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
